version: '3.1'
services:
    web:
        image: ${DTR_URL}/dev/dlogo:${TAG}
        ports:
            - 5021:80
        labels:
            - "com.docker.ucp.mesh.http.80=internal_port=80,external_route=http://dlogo.jcolandr.dtcntr.net"
        networks:
            - ucp-hrm
