version: '3.1'

services:
    web:
        image: ${DTR_URL}/prod/dlogo:stable
        deploy:
            labels:
                com.docker.ucp.mesh.http.80: "external_route=http://dlogo.jcolandr.dtcntr.net,internal_port=80"
        ports:
            - 5021:80
        networks:
            - ucp-hrm

networks:
    ucp-hrm:
        external: true
