version: '3.3'

services:
    web:
        image: ${DTR_URL}/demo/docker-demo:latest
        deploy:
          mode: replicated
          replicas: 4
          labels:
            - "com.docker.lb.hosts=dlogo.west.us.se.dckr.org"
            - "com.docker.lb.port=80"
