version: '3.3'

services:
    dlogo:
        image: ${DOCKER_REGISTRY_HOSTNAME}/${DOCKER_IMAGE_NAMESPACE_PROD}/${DOCKER_IMAGE_REPOSITORY}:${DOCKER_IMAGE_TAG}
        deploy:
          mode: replicated
          replicas: 4
          labels:
            - "com.docker.lb.hosts=dlogo.west.us.se.dckr.org"
            - "com.docker.lb.port=80"
