version: '3.1'

services:
    web:
        image: ${DTR_URL}/demo/docker-demo:latest
        deploy:
            labels:
                com.docker.ucp.mesh.http.80: "external_route=http://dlogo.jcolandr.dtcntr.net,internal_port=80"
        ports:
            - 5021:80
        networks:
            - docker_demo

networks:
    docker_demo:
